### PR TITLE
Add support for 2FA

### PR DESCRIPTION
**Pull request by nevets963**
I followed the implementation from the Python client for 2FA, found here: https://github.com/femueller/python-n26/blob/5428d622bef287d5302fcbe96849e0ed15d04de4/n26/api.py#L376

### CODE REVIEW

**Review by zNoobs — APPROVED** [review]
Tested & approved, it works!

**Comment by leuchte** [comment]
Thank you guys!

**Comment by nevets963** [comment]
@leuchte Could you submit an update to packagist? Thanks!

**Comment by leuchte** [comment]
Yeah, sure. Done.

**Pull request merged**
